### ISSUE TITLE
update subtitle for "To Break or not to Break?"

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/Sounding#1]
1) The subtitle of the "To break or not to break" essay is an old one.  While I was looking at the one that I'd sent through most recently, though, I decided it wasn't really clear.  Could you please rename that essay:
“To Break or not to Break? Emily Tennyson’s scansion of ‘Break, break, break’”

**Comment by thehabes** [comment]
Added this in to the title.  If we need to make a <subtitle> tag for these we can switch it.
