### ISSUE TITLE
Emily's Music Essay - quick post

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/Sounding#14]
Post into the data for visibility, not heavily annotated yet.

[3ET_MSmusicBooks_Essay_PW.docx](https://files.zenhub.io/56bba00ed6cd966c0f84886d)

Here's the next essay (attached) - it's one of the general ones (not specific to "Break, break, break") - more I think of it, I like Donal's idea of categorizing them by type.

**Comment by thehabes** [comment]
Uploaded "completed" essay.  Needs to be tested and checked.

**Comment by cubap** [comment]
[4Publish_Perform_Essay_PW.docx](https://github.com/CenterForDigitalHumanities/Sounding/files/177060/4Publish_Perform_Essay_PW.docx)

@thehabes This is the last one, if you have time to post it.

**Comment by thehabes** [comment]
I can do it

**Comment by cubap** [comment]
Within a week or so - not really urgent.

Patrick Cuba
Center for Digital Humanities
Saint Louis University
314-977-4249

On Wed, Mar 16, 2016 at 6:49 PM, Bryan Haberberger <notifications@github.com
