### ISSUE TITLE
Permissions Disclaimer

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/Sounding#29]
and link in footer for it.

[Copyright_Permissions_PW.docx](https://files.zenhub.io/56cb5931058479ba5b2fbeae)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by thehabes** [comment]
permissions.html added to the static folder.  The copy is all in there and HTML encoded with classed elements, but the HTML to hammer out the specific style needs to be written still.
