### ISSUE TITLE
About Page updated content

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/Sounding#30]
including some dynamic elements.

[About_PW_EJ.docx](https://files.zenhub.io/56cb59e2058479ba5b2fbec4)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by thehabes** [comment]
This has all been put into about.html and made a web page.  Content has been HTML encoded and classed, but the CSS actually has to be written.  I do not know the specifics, but I can go ahead with it if desired.

**Comment by cubap** [comment]
Final fix and checked.
